/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: flow.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "flow.pb-c.h"
void   flowpb__flow_message__init
                     (Flowpb__FlowMessage         *message)
{
  static const Flowpb__FlowMessage init_value = FLOWPB__FLOW_MESSAGE__INIT;
  *message = init_value;
}
size_t flowpb__flow_message__get_packed_size
                     (const Flowpb__FlowMessage *message)
{
  assert(message->base.descriptor == &flowpb__flow_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t flowpb__flow_message__pack
                     (const Flowpb__FlowMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &flowpb__flow_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t flowpb__flow_message__pack_to_buffer
                     (const Flowpb__FlowMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &flowpb__flow_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Flowpb__FlowMessage *
       flowpb__flow_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Flowpb__FlowMessage *)
     protobuf_c_message_unpack (&flowpb__flow_message__descriptor,
                                allocator, len, data);
}
void   flowpb__flow_message__free_unpacked
                     (Flowpb__FlowMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &flowpb__flow_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue flowpb__flow_message__flow_type__enum_values_by_number[6] =
{
  { "FLOWUNKNOWN", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__FLOWUNKNOWN", 0 },
  { "SFLOW_5", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__SFLOW_5", 1 },
  { "NETFLOW_V5", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__NETFLOW_V5", 2 },
  { "NETFLOW_V9", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__NETFLOW_V9", 3 },
  { "IPFIX", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__IPFIX", 4 },
  { "NDPI", "FLOWPB__FLOW_MESSAGE__FLOW_TYPE__NDPI", 5 },
};
static const ProtobufCIntRange flowpb__flow_message__flow_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex flowpb__flow_message__flow_type__enum_values_by_name[6] =
{
  { "FLOWUNKNOWN", 0 },
  { "IPFIX", 4 },
  { "NDPI", 5 },
  { "NETFLOW_V5", 2 },
  { "NETFLOW_V9", 3 },
  { "SFLOW_5", 1 },
};
const ProtobufCEnumDescriptor flowpb__flow_message__flow_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "flowpb.FlowMessage.FlowType",
  "FlowType",
  "Flowpb__FlowMessage__FlowType",
  "flowpb",
  6,
  flowpb__flow_message__flow_type__enum_values_by_number,
  6,
  flowpb__flow_message__flow_type__enum_values_by_name,
  1,
  flowpb__flow_message__flow_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor flowpb__flow_message__field_descriptors[53] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, type),
    &flowpb__flow_message__flow_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampling_rate",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, sampling_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_num",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, sequence_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_addr",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_addr",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packets",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, packets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampler_address",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, sampler_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_hop",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, next_hop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_hop_as",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, next_hop_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_as",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_as",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_as),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_net",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_net),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_net",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_net),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_if",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_if),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "out_if",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, out_if),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_port",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_port",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_tos",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, ip_tos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forwarding_status",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, forwarding_status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_ttl",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, ip_ttl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_flags",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, tcp_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_mac",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_mac",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan_id",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, vlan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "etype",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, etype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp_type",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, icmp_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icmp_code",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, icmp_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_vlan",
    33,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, src_vlan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_vlan",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, dst_vlan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment_id",
    35,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, fragment_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment_offset",
    36,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, fragment_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_flow_label",
    37,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, ipv6_flow_label),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_flags",
    38,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, ip_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observation_domain_id",
    70,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, observation_domain_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "observation_point_id",
    71,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, observation_point_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mpls_ttl",
    80,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Flowpb__FlowMessage, n_mpls_ttl),
    offsetof(Flowpb__FlowMessage, mpls_ttl),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mpls_label",
    81,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Flowpb__FlowMessage, n_mpls_label),
    offsetof(Flowpb__FlowMessage, mpls_label),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mpls_ip",
    82,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Flowpb__FlowMessage, n_mpls_ip),
    offsetof(Flowpb__FlowMessage, mpls_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bgp_next_hop",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, bgp_next_hop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bgp_communities",
    101,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Flowpb__FlowMessage, n_bgp_communities),
    offsetof(Flowpb__FlowMessage, bgp_communities),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "as_path",
    102,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Flowpb__FlowMessage, n_as_path),
    offsetof(Flowpb__FlowMessage, as_path),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_received_ns",
    110,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, time_received_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_flow_start_ns",
    111,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, time_flow_start_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_flow_end_ns",
    112,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, time_flow_end_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_src_addr",
    206,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_src_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_dst_addr",
    207,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_dst_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_proto",
    220,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_src_port",
    221,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_dst_port",
    222,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, in_dst_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vnid",
    223,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, vnid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_proto",
    224,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Flowpb__FlowMessage, app_proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned flowpb__flow_message__field_indices_by_name[] = {
  52,   /* field[52] = app_proto */
  42,   /* field[42] = as_path */
  41,   /* field[41] = bgp_communities */
  40,   /* field[40] = bgp_next_hop */
  5,   /* field[5] = bytes */
  4,   /* field[4] = dst_addr */
  11,   /* field[11] = dst_as */
  24,   /* field[24] = dst_mac */
  13,   /* field[13] = dst_net */
  18,   /* field[18] = dst_port */
  30,   /* field[30] = dst_vlan */
  26,   /* field[26] = etype */
  20,   /* field[20] = forwarding_status */
  31,   /* field[31] = fragment_id */
  32,   /* field[32] = fragment_offset */
  28,   /* field[28] = icmp_code */
  27,   /* field[27] = icmp_type */
  47,   /* field[47] = in_dst_addr */
  50,   /* field[50] = in_dst_port */
  14,   /* field[14] = in_if */
  48,   /* field[48] = in_proto */
  46,   /* field[46] = in_src_addr */
  49,   /* field[49] = in_src_port */
  34,   /* field[34] = ip_flags */
  19,   /* field[19] = ip_tos */
  21,   /* field[21] = ip_ttl */
  33,   /* field[33] = ipv6_flow_label */
  39,   /* field[39] = mpls_ip */
  38,   /* field[38] = mpls_label */
  37,   /* field[37] = mpls_ttl */
  8,   /* field[8] = next_hop */
  9,   /* field[9] = next_hop_as */
  35,   /* field[35] = observation_domain_id */
  36,   /* field[36] = observation_point_id */
  15,   /* field[15] = out_if */
  6,   /* field[6] = packets */
  16,   /* field[16] = proto */
  7,   /* field[7] = sampler_address */
  1,   /* field[1] = sampling_rate */
  2,   /* field[2] = sequence_num */
  3,   /* field[3] = src_addr */
  10,   /* field[10] = src_as */
  23,   /* field[23] = src_mac */
  12,   /* field[12] = src_net */
  17,   /* field[17] = src_port */
  29,   /* field[29] = src_vlan */
  22,   /* field[22] = tcp_flags */
  45,   /* field[45] = time_flow_end_ns */
  44,   /* field[44] = time_flow_start_ns */
  43,   /* field[43] = time_received_ns */
  0,   /* field[0] = type */
  25,   /* field[25] = vlan_id */
  51,   /* field[51] = vnid */
};
static const ProtobufCIntRange flowpb__flow_message__number_ranges[10 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 6, 3 },
  { 9, 5 },
  { 70, 35 },
  { 80, 37 },
  { 100, 40 },
  { 110, 43 },
  { 206, 46 },
  { 220, 48 },
  { 0, 53 }
};
const ProtobufCMessageDescriptor flowpb__flow_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "flowpb.FlowMessage",
  "FlowMessage",
  "Flowpb__FlowMessage",
  "flowpb",
  sizeof(Flowpb__FlowMessage),
  53,
  flowpb__flow_message__field_descriptors,
  flowpb__flow_message__field_indices_by_name,
  10,  flowpb__flow_message__number_ranges,
  (ProtobufCMessageInit) flowpb__flow_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
